### ISSUE TITLE
Zwischenpräsentation erstellen

### ISSUE THREAD

**Issue by Canoobi** [Software-Engineering-I-HWR/GourmetGuide#17]
- Vortragszeit: Vortragszeit pro Teammitglied 4 Minuten, Diskussion/Fragen pro Teammitglied 1 Minute
- Inhalte sind grundsätzlich frei wählbar, Ideen sind hier: Projektidee, Rollenverteilung im Team, gewählte Technologien, Aufwandskalkulation (Planzahlen), besondere Herausforderungen bisher, Status quo der Entwicklung (inkl. Demo), ...

**Comment by Canoobi** [comment]
Themenaufteilung:
Josi:
- Demo Website
- Rollenverteilung im Team
Tobias:
- Demo PDF-Erstellung
- Projektidee
Sven:
- Aufwandskalkulation (Planzahlen)
Carlo:
- gewählte Technologien
- besondere Herausforderungen bisher

**Comment by TOH01** [comment]
abfrage1:
curl -X POST http://localhost:3000/generate-pdf -H "Content-Type: application/json" -d '{
  "name": "Pfannkuchen",
  "image": "https://raw.githubusercontent.com/Software-Engineering-I-HWR/GourmetGuide/refs/heads/pdf-branch/backend/assets/Pfannkuchen-10-von-13.png",
  "description": "Ein einfaches Rezept fuer leckere Pfannkuchen.",
  "ingredients": [
    "2 Tassen Mehl",
    "1 Essloeffel Zucker",
    "1 Teeloeffel Backpulver",
    "1/2 Teeloeffel Salz",
    "1 Tasse Milch",
    "2 Eier"
  ]
}' --output recipe.pdf

abfrage2: 
curl -X POST http://localhost:3000/generate-pdf -H "Content-Type: application/json" -d '{
"name": "Pfannkuchen",
"image": "https://raw.githubusercontent.com/Software-Engineering-I-HWR/GourmetGuide/refs/heads/pdf-branch/backend/assets/Pfannkuchen-10-von-13.png",
"description": "Pfannkuchen sind ein echter Klassiker, der in vielen verschiedenen Varianten auf der ganzen Welt genossen wird. Dieses Rezept bietet die perfekte Balance zwischen suessem Geschmack und einer fluffigen, zarten Konsistenz. Die Zubereitung ist kinderleicht und erfordert nur wenige Zutaten, die fast immer im Haushalt vorrätig sind. Mehl, Eier, Milch und eine Prise Zucker sind die Basis fuer einen Teig, der in der Pfanne zu goldbraunen Pfannkuchen gebacken wird. Fuer eine besondere Note koennen Sie dem Teig Vanilleextrakt oder geriebene Zitronenschale hinzufuegen. Servieren Sie die Pfannkuchen mit frischen Fruechten, Ahornsirup oder sogar einer herzhaften Fuellung aus Kaese und Schinken. Diese Flexibilitaet macht Pfannkuchen zu einer hervorragenden Wahl fuer jede Tageszeit – ob zum Fruehstueck, Mittagessen oder Abendessen. Probieren Sie auch verschiedene Toppings wie Schokolade, Honig oder Marmelade, um Ihrer Kreation eine suesse Note zu geben. Alternativ koennen Sie eine herzhafte Version ausprobieren, indem Sie beispielsweise Speck und Kaese verwenden. Pfannkuchen lassen sich einfach anpassen, indem Sie den Teig mit Gewuerzen oder Kräutern aufpeppen oder sogar geraffeltes Gemuese unterheben. Der Teig selbst kann leicht an die Vorlieben Ihrer Familie angepasst werden, sodass Sie sicher sein koennen, dass jeder auf seine Kosten kommt. Perfekt zum Fruehstueck oder als Dessert, aber auch als vollwertige Mahlzeit mit herzhaften Beilagen. Pfannkuchen sind die ideale Basis fuer kulinarische Experimente – von klassisch bis ausgefallen. Guten Appetit!",
"ingredients": [
"2 Tassen Mehl",
"1 Essloeffel Zucker",
"1 Teeloeffel Backpulver",
"1/2 Teeloeffel Salz",
"1 Tasse Milch",
"2 Eier",
"Eine grosszuegige Prise Vanilleextrakt, um den Geschmack zu verfeinern"
]
}' --output recipe.pdf

**Comment by TOH01** [comment]
https://raw.githubusercontent.com/Software-Engineering-I-HWR/GourmetGuide/refs/heads/main/Backend/PDF-Share/assets/Pfannkuchen-10-von-13.png
