### ISSUE TITLE
Festlegen von Programmiersprachen, Design etc.

### ISSUE THREAD

**Issue by Canoobi** [Software-Engineering-I-HWR/GourmetGuide#2]
Wir reden über die Sachen, die noch festgelegt werden müssen und halten sie hier fest:
- Frontend: TS mit React
- Backend: TS
- Datenbank: MariaDB (auf Carlos Server)
- Hosten: Datenbank und API auf dem Server; Webseite noch nicht klar.

**Comment by blnpurple** [comment]
- Grobkonzept für Design und Aufbau
