### ISSUE TITLE
PDF erstellen

### ISSUE THREAD

**Issue by Canoobi** [Software-Engineering-I-HWR/GourmetGuide#21]

**Comment by TOH01** [comment]
Curl Request to get example pdf: 
curl -X POST http://localhost:3000/generate-pdf -H "Content-Type: application/json" --output recipe.pdf

**Comment by TOH01** [comment]
![REZEPTNAME](https://github.com/user-attachments/assets/21897a79-162a-4a74-bb32-18716f0c557c)

First draft for PDF layout

**Comment by TOH01** [comment]
Bearbeitet von 10:30 bis 12:00 => 90 Minuten

**Comment by TOH01** [comment]
12:45 bis 13:15 => 30 Minuten

TODO : 

1. Bild von Rezept einfügen
2. Fehler bei zu langen Texten beheben

**Comment by TOH01** [comment]
curl -X POST http://localhost:3000/generate-pdf -H "Content-Type: application/json" -d '{
    "name": "Pfannkuchen",
    "image": "https://raw.githubusercontent.com/Software-Engineering-I-HWR/GourmetGuide/refs/heads/pdf-branch/backend/assets/Pfannkuchen-10-von-13.png",
    "description": "A delicious pancake recipe.",
    "ingredients": [
        "2 Tassen Mehl",
        "1 Esslöffel Zucker",
        "1 Teelöffel Backpulver",
        "1/2 Teelöffel Salz",
        "1 Tasse Milch",
        "2 Eier"
    ]
}' --output recipe.pdf

Downloads file to location from where command was executed.

**Comment by TOH01** [comment]
[recipe.pdf](https://github.com/user-attachments/files/17078192/recipe.pdf)
Output

**Comment by TOH01** [comment]
Ungefähr nochmal insgesamt 3 Stunden zu verschiedenen Zeiten dran gearbeitet.
