### ISSUE TITLE
Unterseite Zutatensuche

### ISSUE THREAD

**Issue by Canoobi** [Software-Engineering-I-HWR/GourmetGuide#22]

**Comment by GrubieKreatur** [comment]
1:30

**Comment by GrubieKreatur** [comment]
30 min fehler behebung mit änderung zu schnelle seiten änderung

**Comment by GrubieKreatur** [comment]
2 Stunden Unter seiten verwaltung Home Seite als eigenständige Seite. Standart Elemente auf jeder seite angezeigen
