### ISSUE TITLE
Login backend

### ISSUE THREAD

**Issue by Canoobi** [Software-Engineering-I-HWR/GourmetGuide#9]
AK:
-compare login with db
-get login from user
-set cookie if logged in
Time:
1:45 h

**Comment by TOH01** [comment]
Backend Test with Curl, execute Commands in Bash after running backend
(click green arrow next to start and wait for server running localhost):

Backend Test for Login Branch:

curl -X POST http://localhost:3000/login \
-H "Content-Type: application/json" \
-d '{"email":"test@example.com", "password":"password123"}'

Response : {"message":"Login successful"}


$ curl -X POST http://localhost:3000/login \
-H "Content-Type: application/json" \
-d '{"email":"test@example.com", "password":"password"}'

Response : {"message":"Invalid credentials"}

**Comment by TOH01** [comment]
If password input contains characters like \ or ' or " there are problems.
